# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMpipeline-connection'
    subscriptionId: '8cc14d1d-6f8e-4a80-ba91-058979b66fc2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMpipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/adit-devops17/azure-pipeline/main/webapp/azuredeploy.json'
    overrideParameters: '-projectName azure-pipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

